seedが作成できない
nn12vl9l/laravel_crm pull request #1
Opened 2021-09-27 05:46 UTC by nn12vl9l

Factoryの登録の作業にて、DatabaseSeeder.phpにfactoryを呼び出すコードを記載しましたが、
作成ができず、またエラー箇所の特定ができないです。
恐れ入りますが、ご確認お願い致します。

2021-09-27 15:45 UTC, kazu-taka commented on app/Http/Controllers/CustomerController.php
> +        $customer = new Customer();
@nn12vl9l 
オークションアプリのupdateアクションと異なる部分があるので確認してみてください！

2021-09-29 04:58 UTC, nn12vl9l commented
<img width="1440" alt="スクリーンショット 2021-09-29 13 47 32" src="https://user-images.githubusercontent.com/64241250/135205841-a8060fe2-e743-455e-a57a-1c32fab7a0a6.png">
<img width="1440" alt="スクリーンショット 2021-09-29 13 47 42" src="https://user-images.githubusercontent.com/64241250/135205854-82b8abc8-70f7-4042-b49a-10e5a7571d5c.png">
<img width="1440" alt="スクリーンショット 2021-09-29 13 48 07" src="https://user-images.githubusercontent.com/64241250/135205855-5a50bd76-c717-4248-b178-8df2c7ce87fe.png">
<img width="1440" alt="スクリーンショット 2021-09-29 13 48 25" src="https://user-images.githubusercontent.com/64241250/135205856-8fe1cade-fc19-4819-b18d-611b929fcf41.png">
<img width="1440" alt="スクリーンショット 2021-09-29 13 48 41" src="https://user-images.githubusercontent.com/64241250/135205857-c0b55092-6b4a-4dea-9908-53af197b6d8a.png">
<img width="1440" alt="スクリーンショット 2021-09-29 13 48 55" src="https://user-images.githubusercontent.com/64241250/135205859-a3cda7ca-f90f-499c-967d-2d6e44ba6a94.png">
<img width="1440" alt="スクリーンショット 2021-09-29 13 49 13" src="https://user-images.githubusercontent.com/64241250/135205860-91861ea9-dd9d-4ba2-915e-f9e37f734dd2.png">

2021-09-29 05:12 UTC, kazu-taka requested changes
@nn12vl9l 
プルリクエストのスクリーンショットが欲しかったです^^;
カラム名の修正と、それに関わる修正をお願いします🙇

2021-09-29 05:12 UTC, kazu-taka commented on app/Http/Controllers/CustomerController.php
> +            // dd($th);
@nn12vl9l 
不要なコメントは削除お願いします！

2021-09-29 05:12 UTC, kazu-taka commented on app/Http/Requests/CustomerRequest.php
> +            'phoneNumber' => 'required|string'
@nn12vl9l 
日本国内の場合、郵便番号は7桁、電話番号は10桁か11桁になるので、バリデーションに追加しても良いかと思います✨

2021-09-29 05:12 UTC, kazu-taka commented on database/migrations/2021_09_26_131129_create_customers_table.php
> +            $table->string('phoneNumber');
@nn12vl9l 
Laravelで複数の単語でカラムを作成する場合は、phone_numberのようにスネークケースでお願いします✨

2021-09-29 05:14 UTC, kazu-taka commented
@nn12vl9l 
スクショありましたね^^;
ありがとうございます✨

2021-09-29 05:58 UTC, kazu-taka commented
@nn12vl9l 
問題ないのでマージしてOKです👍
![LGTM](https://image.lgtmoon.dev/82603)

2021-09-29 06:07 UTC, merged